# Basic Information 
title: Yifei Deng
position: Assistant Researcher
affiliation: Anhui University
email: yf-ah@foxmail.com

# Search Engine Optimization (SEO)
keywords: cross-modal person retrieval, multimodal visual grounding, embodied search, multimodal learning
description: Personal academic homepage of Yifei Deng, focusing on cross-modal person retrieval, multimodal visual grounding, and embodied AI.
canonical: https://yifei-ahu.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=3s_j68IAAAAJ&hl=zh-CN
cv_link: ./assets/files/Yifei_Deng_CV.pdf
github_link: https://github.com/Yifei-AHU
wechat_qr: /assets/img/wechat_qr.jpg

# Images
avatar: ./assets/img/img.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Visitor Analytics
goatcounter_code: yifei-ahu

# Google Analytics
# Delete this line if you don't use Google Analytics.
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
